Disable dependabot for campaign 2022
wmde/fundraising-phpcs pull request #12
Opened 2022-11-02 07:42 UTC by Sperling-0

2022-11-02 15:22 UTC, moiikana requested changes
some files of the .idea folder slipped into the PR, should be removed from the commit

2022-11-14 08:13 UTC, Abban commented
@Sperling-0 Do you need help on how to sort this?

2022-11-16 17:19 UTC, gbirke approved these changes

2022-11-17 13:25 UTC, moiikana approved these changes

2023-01-10 09:54 UTC, Abban commented
Closing this because the campaign is over.

2023-01-10 09:54 UTC, closed without merging